### ISSUE TITLE
q2a-hashtagger :about mentions with two or more names and special characters

### ISSUE THREAD

**Issue by SEIKAKU** [pupi1985/q2a-hashtagger#1]
@pupi1985 i read the instructions and works fine whit @names
But if you put @"name1 name2", this dont work to mentions
for example @"Mr Rick"
How it supuse that It be may work?

Can you help.

best regards
Monkey

**Comment by pupi1985** [comment]
Let me see if I undertsnad.

You're saying you have this URL:
`https://yoursite.com/user/Mr%20Rick` (the handle would be `Mr Rick`)

And you cannot tag this user using `@"Mr Rick"`

Is this correct?

**Comment by SEIKAKU** [comment]
Yeah that's right .with two names I have tried to use the mention so that hastagger does his function but there is no success.

**Comment by pupi1985** [comment]
Please, test v1.2.5 and reply back.

Note the users won't be able to be mentioned by `@"XXXXX" `anymore. Same with `@XXXXX`.

Now they can only be mentioned with `@XXXXXX@` (with a closing `@` always). The good thing is that all special characters can be used to mention a user now :)

**Comment by SEIKAKU** [comment]
works. a small step in the code and a big jump for q2a
Thank you very much

**Comment by pupi1985** [comment]
The step in the code wasn't that small... it took me 3 hours to get that fixed >.<
